# Generated by Django 4.2.10 on 2024-02-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_main', '0003_room_booked_room_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='booked_room_status',
        ),
        migrations.AddField(
            model_name='bookroom',
            name='booked_room_status',
            field=models.CharField(choices=[('booked', 'Booked'), ('pending', 'Pending'), ('canceled', 'Canceled')], default='pending', max_length=255),
        ),
    ]
