# Generated by Django 4.2.10 on 2024-02-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_main', '0004_remove_room_booked_room_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='photos',
            field=models.ImageField(default='images/room-1.jpg', help_text='Upload photos of the room.', upload_to='images/rooms/'),
        ),
    ]
