# Generated by Django 4.2.10 on 2024-02-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='photos',
            field=models.ImageField(default='images/room-1.jpg', help_text='Upload photos of the room.', upload_to='images/'),
        ),
    ]
