# Generated by Django 4.2.10 on 2024-02-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_main', '0002_room_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='booked_room_status',
            field=models.CharField(choices=[('booked', 'Booked'), ('pending', 'Pending'), ('canceled', 'Canceled')], default='pending', max_length=255),
        ),
    ]
